language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.4
  - 2.3.0
  - ruby-head

before_install: gem install bundler -v 1.10.6

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - nikitaavvakumov@gmail.com
    on_success: change
    on_failure: always
